// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1580620262);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 537);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1580620231);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"53014\":1580620240135,\"53018\":1580620240209,\"53035\":1580620240135,\"53041\":1580620240135}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.spoc.impressions", "{\"2345\":[1580620240229]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{5a189814-f887-4cbf-a6e4-198742e67aca}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1580620280214");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1580622050214");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1580620248210");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1580623848210");
user_pref("browser.search.cohort", "apr18-1");
user_pref("browser.search.region", "US");
user_pref("browser.slowStartup.averageTime", 1497);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20191113205532");
user_pref("browser.startup.homepage_override.mstone", "68.2.0");
user_pref("browser.startup.lastColdStartupCheck", 1580620233);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.2.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.2.0");
user_pref("extensions.lastPlatformVersion", "68.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"78e968e2-8afc-4283-b8b2-2834f4341a14\",\"fxmonitor@mozilla.org\":\"a493dd0d-59e7-4676-858e-da44c0ee7a56\",\"screenshots@mozilla.org\":\"6e941330-ed48-4b40-8da9-480801520a80\",\"webcompat-reporter@mozilla.org\":\"1ddbd1fa-9161-4070-a570-0821ab3bd631\",\"webcompat@mozilla.org\":\"f1b47a87-cd7c-4cc5-a3fc-82390c1560bc\",\"default-theme@mozilla.org\":\"4c87090e-0014-4c03-ac71-2503ca0ba10e\",\"google@search.mozilla.org\":\"9d7c63bd-6019-4f29-9778-ee361ee7c507\",\"amazondotcom@search.mozilla.org\":\"4ea2e673-ba8b-40f5-96fb-bee1f20db4a7\",\"bing@search.mozilla.org\":\"227d3f6b-b5f0-49d6-8294-ae949adeecf5\",\"ddg@search.mozilla.org\":\"6abf05a0-aeb5-460a-82d8-def53785bb67\",\"ebay@search.mozilla.org\":\"8dccc347-ecfe-4a78-aade-d9e2194a06dc\",\"twitter@search.mozilla.org\":\"b39074e3-ec5c-4d0b-8e0b-75f7af7ef814\",\"wikipedia@search.mozilla.org\":\"d4f935bb-ede4-4060-9f71-922674774406\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "bf2db4a0-eabe-495a-8565-c150bb412466");
user_pref("security.sandbox.plugin.tempDirSuffix", "43b28122-03ba-4693-837a-e87efd59224a");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1580620231);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20191113205532");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
